### ISSUE TITLE
Roadmap : v1

### ISSUE THREAD

**Issue by anikethsaha** [anikethsaha/htmllinter#3]
## 1. Configuration

- [ ] rules
- [ ] standards
- [ ] plugins
- [ ] extend

## 2 Test

- [ ] CLI
- [ ] rules
- [ ] standards
- [ ] plugins
- [ ] extend
- [ ] `@htmllinter/basic-standard`

## 3. Package development

- [ ] `core`
    - [ ] API
    - [ ] CLI
    - [ ] support for extending `configs`
    - [ ] support for `plugins`
    - [ ] support for `standards`
    - [ ] support for `rules`

- [ ] `basic-standard`

- [ ] `basic-config`

## CI

- [ ] fix the GH action for `cli.test.js`
